
## Create a docker compose file to run python
services:
  app:
    build: .
    container_name: resume-ranking
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - "8080:80"
    volumes:
      - .:/usr/src/app

